spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
  redis:
    host: 192.168.1.94
    password: 123456
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
  kafka:
    bootstrap-servers: 192.168.1.94:9092
    topic:
      Name: secKill #自定义topic名称
      numPartitions: 1  #自定义分区
      replicationFactor: 1 #自定义副本
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1

    consumer:
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000
      group-id: seckill-group

mybatis-plus:
  typeAliasesPackage: com.zzw.seckill.seckillmain.entity
  mapper-locations:
    - classpath*:com.zzw.seckill.seckillmain/**/mapping/*.xml
    - classpath*:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: Y
      logic-not-delete-value: N
      field-strategy: not_null
      id-type: ID_WORKER
      db-type: mysql